// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: saga/saga.proto

package saga

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartCheckoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Cart          []*Cart                `protobuf:"bytes,2,rep,name=cart,proto3" json:"cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartCheckoutRequest) Reset() {
	*x = StartCheckoutRequest{}
	mi := &file_saga_saga_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCheckoutRequest) ProtoMessage() {}

func (x *StartCheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saga_saga_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCheckoutRequest.ProtoReflect.Descriptor instead.
func (*StartCheckoutRequest) Descriptor() ([]byte, []int) {
	return file_saga_saga_proto_rawDescGZIP(), []int{0}
}

func (x *StartCheckoutRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *StartCheckoutRequest) GetCart() []*Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

type StartCheckoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderID       string                 `protobuf:"bytes,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartCheckoutResponse) Reset() {
	*x = StartCheckoutResponse{}
	mi := &file_saga_saga_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCheckoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCheckoutResponse) ProtoMessage() {}

func (x *StartCheckoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_saga_saga_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCheckoutResponse.ProtoReflect.Descriptor instead.
func (*StartCheckoutResponse) Descriptor() ([]byte, []int) {
	return file_saga_saga_proto_rawDescGZIP(), []int{1}
}

func (x *StartCheckoutResponse) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

func (x *StartCheckoutResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Cart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     int64                  `protobuf:"varint,1,opt,name=productID,proto3" json:"productID,omitempty"`
	Price         int64                  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cart) Reset() {
	*x = Cart{}
	mi := &file_saga_saga_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cart) ProtoMessage() {}

func (x *Cart) ProtoReflect() protoreflect.Message {
	mi := &file_saga_saga_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cart.ProtoReflect.Descriptor instead.
func (*Cart) Descriptor() ([]byte, []int) {
	return file_saga_saga_proto_rawDescGZIP(), []int{2}
}

func (x *Cart) GetProductID() int64 {
	if x != nil {
		return x.ProductID
	}
	return 0
}

func (x *Cart) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Cart) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_saga_saga_proto protoreflect.FileDescriptor

const file_saga_saga_proto_rawDesc = "" +
	"\n" +
	"\x0fsaga/saga.proto\x12\n" +
	"proto_saga\"T\n" +
	"\x14StartCheckoutRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x03R\x06userID\x12$\n" +
	"\x04cart\x18\x02 \x03(\v2\x10.proto_saga.CartR\x04cart\"G\n" +
	"\x15StartCheckoutResponse\x12\x18\n" +
	"\aorderID\x18\x01 \x01(\tR\aorderID\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"V\n" +
	"\x04Cart\x12\x1c\n" +
	"\tproductID\x18\x01 \x01(\x03R\tproductID\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x03R\x05price\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity2\\\n" +
	"\x04Saga\x12T\n" +
	"\rStartCheckout\x12 .proto_saga.StartCheckoutRequest\x1a!.proto_saga.StartCheckoutResponseB.Z,github.com/vsespontanno/eCommerce/proto/sagab\x06proto3"

var (
	file_saga_saga_proto_rawDescOnce sync.Once
	file_saga_saga_proto_rawDescData []byte
)

func file_saga_saga_proto_rawDescGZIP() []byte {
	file_saga_saga_proto_rawDescOnce.Do(func() {
		file_saga_saga_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_saga_saga_proto_rawDesc), len(file_saga_saga_proto_rawDesc)))
	})
	return file_saga_saga_proto_rawDescData
}

var file_saga_saga_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_saga_saga_proto_goTypes = []any{
	(*StartCheckoutRequest)(nil),  // 0: proto_saga.StartCheckoutRequest
	(*StartCheckoutResponse)(nil), // 1: proto_saga.StartCheckoutResponse
	(*Cart)(nil),                  // 2: proto_saga.Cart
}
var file_saga_saga_proto_depIdxs = []int32{
	2, // 0: proto_saga.StartCheckoutRequest.cart:type_name -> proto_saga.Cart
	0, // 1: proto_saga.Saga.StartCheckout:input_type -> proto_saga.StartCheckoutRequest
	1, // 2: proto_saga.Saga.StartCheckout:output_type -> proto_saga.StartCheckoutResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_saga_saga_proto_init() }
func file_saga_saga_proto_init() {
	if File_saga_saga_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_saga_saga_proto_rawDesc), len(file_saga_saga_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_saga_saga_proto_goTypes,
		DependencyIndexes: file_saga_saga_proto_depIdxs,
		MessageInfos:      file_saga_saga_proto_msgTypes,
	}.Build()
	File_saga_saga_proto = out.File
	file_saga_saga_proto_goTypes = nil
	file_saga_saga_proto_depIdxs = nil
}
