// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/saga/saga.proto

package saga

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Saga_StartCheckout_FullMethodName = "/proto_saga.Saga/StartCheckout"
)

// SagaClient is the client API for Saga service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SagaClient interface {
	StartCheckout(ctx context.Context, in *StartCheckoutRequest, opts ...grpc.CallOption) (*StartCheckoutResponse, error)
}

type sagaClient struct {
	cc grpc.ClientConnInterface
}

func NewSagaClient(cc grpc.ClientConnInterface) SagaClient {
	return &sagaClient{cc}
}

func (c *sagaClient) StartCheckout(ctx context.Context, in *StartCheckoutRequest, opts ...grpc.CallOption) (*StartCheckoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartCheckoutResponse)
	err := c.cc.Invoke(ctx, Saga_StartCheckout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SagaServer is the server API for Saga service.
// All implementations must embed UnimplementedSagaServer
// for forward compatibility.
type SagaServer interface {
	StartCheckout(context.Context, *StartCheckoutRequest) (*StartCheckoutResponse, error)
	mustEmbedUnimplementedSagaServer()
}

// UnimplementedSagaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSagaServer struct{}

func (UnimplementedSagaServer) StartCheckout(context.Context, *StartCheckoutRequest) (*StartCheckoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartCheckout not implemented")
}
func (UnimplementedSagaServer) mustEmbedUnimplementedSagaServer() {}
func (UnimplementedSagaServer) testEmbeddedByValue()              {}

// UnsafeSagaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SagaServer will
// result in compilation errors.
type UnsafeSagaServer interface {
	mustEmbedUnimplementedSagaServer()
}

func RegisterSagaServer(s grpc.ServiceRegistrar, srv SagaServer) {
	// If the following call pancis, it indicates UnimplementedSagaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Saga_ServiceDesc, srv)
}

func _Saga_StartCheckout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartCheckoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SagaServer).StartCheckout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Saga_StartCheckout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SagaServer).StartCheckout(ctx, req.(*StartCheckoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Saga_ServiceDesc is the grpc.ServiceDesc for Saga service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Saga_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto_saga.Saga",
	HandlerType: (*SagaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartCheckout",
			Handler:    _Saga_StartCheckout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/saga/saga.proto",
}
