// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/products/products.proto

package products

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReserveProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductSaga         `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveProductsRequest) Reset() {
	*x = ReserveProductsRequest{}
	mi := &file_proto_products_products_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveProductsRequest) ProtoMessage() {}

func (x *ReserveProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_products_products_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveProductsRequest.ProtoReflect.Descriptor instead.
func (*ReserveProductsRequest) Descriptor() ([]byte, []int) {
	return file_proto_products_products_proto_rawDescGZIP(), []int{0}
}

func (x *ReserveProductsRequest) GetProducts() []*ProductSaga {
	if x != nil {
		return x.Products
	}
	return nil
}

type ProductSaga struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductSaga) Reset() {
	*x = ProductSaga{}
	mi := &file_proto_products_products_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductSaga) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductSaga) ProtoMessage() {}

func (x *ProductSaga) ProtoReflect() protoreflect.Message {
	mi := &file_proto_products_products_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductSaga.ProtoReflect.Descriptor instead.
func (*ProductSaga) Descriptor() ([]byte, []int) {
	return file_proto_products_products_proto_rawDescGZIP(), []int{1}
}

func (x *ProductSaga) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductSaga) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ReserveProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveProductsResponse) Reset() {
	*x = ReserveProductsResponse{}
	mi := &file_proto_products_products_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveProductsResponse) ProtoMessage() {}

func (x *ReserveProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_products_products_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveProductsResponse.ProtoReflect.Descriptor instead.
func (*ReserveProductsResponse) Descriptor() ([]byte, []int) {
	return file_proto_products_products_proto_rawDescGZIP(), []int{2}
}

func (x *ReserveProductsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReserveProductsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReleaseProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductSaga         `protobuf:"bytes,2,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseProductsRequest) Reset() {
	*x = ReleaseProductsRequest{}
	mi := &file_proto_products_products_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseProductsRequest) ProtoMessage() {}

func (x *ReleaseProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_products_products_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseProductsRequest.ProtoReflect.Descriptor instead.
func (*ReleaseProductsRequest) Descriptor() ([]byte, []int) {
	return file_proto_products_products_proto_rawDescGZIP(), []int{3}
}

func (x *ReleaseProductsRequest) GetProducts() []*ProductSaga {
	if x != nil {
		return x.Products
	}
	return nil
}

type ReleaseProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseProductsResponse) Reset() {
	*x = ReleaseProductsResponse{}
	mi := &file_proto_products_products_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseProductsResponse) ProtoMessage() {}

func (x *ReleaseProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_products_products_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseProductsResponse.ProtoReflect.Descriptor instead.
func (*ReleaseProductsResponse) Descriptor() ([]byte, []int) {
	return file_proto_products_products_proto_rawDescGZIP(), []int{4}
}

func (x *ReleaseProductsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReleaseProductsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CommitProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductSaga         `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitProductsRequest) Reset() {
	*x = CommitProductsRequest{}
	mi := &file_proto_products_products_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitProductsRequest) ProtoMessage() {}

func (x *CommitProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_products_products_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitProductsRequest.ProtoReflect.Descriptor instead.
func (*CommitProductsRequest) Descriptor() ([]byte, []int) {
	return file_proto_products_products_proto_rawDescGZIP(), []int{5}
}

func (x *CommitProductsRequest) GetProducts() []*ProductSaga {
	if x != nil {
		return x.Products
	}
	return nil
}

type CommitProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitProductsResponse) Reset() {
	*x = CommitProductsResponse{}
	mi := &file_proto_products_products_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitProductsResponse) ProtoMessage() {}

func (x *CommitProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_products_products_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitProductsResponse.ProtoReflect.Descriptor instead.
func (*CommitProductsResponse) Descriptor() ([]byte, []int) {
	return file_proto_products_products_proto_rawDescGZIP(), []int{6}
}

func (x *CommitProductsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommitProductsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetProductByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductByIDRequest) Reset() {
	*x = GetProductByIDRequest{}
	mi := &file_proto_products_products_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductByIDRequest) ProtoMessage() {}

func (x *GetProductByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_products_products_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductByIDRequest.ProtoReflect.Descriptor instead.
func (*GetProductByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_products_products_proto_rawDescGZIP(), []int{7}
}

func (x *GetProductByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetProductByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Product       *Product               `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductByIDResponse) Reset() {
	*x = GetProductByIDResponse{}
	mi := &file_proto_products_products_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductByIDResponse) ProtoMessage() {}

func (x *GetProductByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_products_products_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductByIDResponse.ProtoReflect.Descriptor instead.
func (*GetProductByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_products_products_proto_rawDescGZIP(), []int{8}
}

func (x *GetProductByIDResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetProductByIDResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type GetProductsByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsByIDRequest) Reset() {
	*x = GetProductsByIDRequest{}
	mi := &file_proto_products_products_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsByIDRequest) ProtoMessage() {}

func (x *GetProductsByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_products_products_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsByIDRequest.ProtoReflect.Descriptor instead.
func (*GetProductsByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_products_products_proto_rawDescGZIP(), []int{9}
}

func (x *GetProductsByIDRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetProductsByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Products      []*Product             `protobuf:"bytes,2,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsByIDResponse) Reset() {
	*x = GetProductsByIDResponse{}
	mi := &file_proto_products_products_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsByIDResponse) ProtoMessage() {}

func (x *GetProductsByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_products_products_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsByIDResponse.ProtoReflect.Descriptor instead.
func (*GetProductsByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_products_products_proto_rawDescGZIP(), []int{10}
}

func (x *GetProductsByIDResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetProductsByIDResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_proto_products_products_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_proto_products_products_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_proto_products_products_proto_rawDescGZIP(), []int{11}
}

func (x *Product) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_proto_products_products_proto protoreflect.FileDescriptor

const file_proto_products_products_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/products/products.proto\x12\x0eproto_products\"Q\n" +
	"\x16ReserveProductsRequest\x127\n" +
	"\bproducts\x18\x01 \x03(\v2\x1b.proto_products.ProductSagaR\bproducts\"9\n" +
	"\vProductSaga\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\"I\n" +
	"\x17ReserveProductsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"Q\n" +
	"\x16ReleaseProductsRequest\x127\n" +
	"\bproducts\x18\x02 \x03(\v2\x1b.proto_products.ProductSagaR\bproducts\"I\n" +
	"\x17ReleaseProductsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"P\n" +
	"\x15CommitProductsRequest\x127\n" +
	"\bproducts\x18\x01 \x03(\v2\x1b.proto_products.ProductSagaR\bproducts\"H\n" +
	"\x16CommitProductsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"'\n" +
	"\x15GetProductByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"a\n" +
	"\x16GetProductByIDResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x121\n" +
	"\aproduct\x18\x02 \x01(\v2\x17.proto_products.ProductR\aproduct\"*\n" +
	"\x16GetProductsByIDRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"d\n" +
	"\x17GetProductsByIDResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x123\n" +
	"\bproducts\x18\x02 \x03(\v2\x17.proto_products.ProductR\bproducts\"e\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price2\xcb\x01\n" +
	"\bProducts\x12_\n" +
	"\x0eGetProductByID\x12%.proto_products.GetProductByIDRequest\x1a&.proto_products.GetProductByIDResponse\x12^\n" +
	"\vGetProducts\x12&.proto_products.GetProductsByIDRequest\x1a'.proto_products.GetProductsByIDResponse2\xb7\x02\n" +
	"\fSagaProducts\x12b\n" +
	"\x0fReserveProducts\x12&.proto_products.ReserveProductsRequest\x1a'.proto_products.ReserveProductsResponse\x12b\n" +
	"\x0fReleaseProducts\x12&.proto_products.ReleaseProductsRequest\x1a'.proto_products.ReleaseProductsResponse\x12_\n" +
	"\x0eCommitProducts\x12%.proto_products.CommitProductsRequest\x1a&.proto_products.CommitProductsResponseB;Z9github.com/vsespontanno/eCommerce/internal/proto/productsb\x06proto3"

var (
	file_proto_products_products_proto_rawDescOnce sync.Once
	file_proto_products_products_proto_rawDescData []byte
)

func file_proto_products_products_proto_rawDescGZIP() []byte {
	file_proto_products_products_proto_rawDescOnce.Do(func() {
		file_proto_products_products_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_products_products_proto_rawDesc), len(file_proto_products_products_proto_rawDesc)))
	})
	return file_proto_products_products_proto_rawDescData
}

var file_proto_products_products_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_products_products_proto_goTypes = []any{
	(*ReserveProductsRequest)(nil),  // 0: proto_products.ReserveProductsRequest
	(*ProductSaga)(nil),             // 1: proto_products.ProductSaga
	(*ReserveProductsResponse)(nil), // 2: proto_products.ReserveProductsResponse
	(*ReleaseProductsRequest)(nil),  // 3: proto_products.ReleaseProductsRequest
	(*ReleaseProductsResponse)(nil), // 4: proto_products.ReleaseProductsResponse
	(*CommitProductsRequest)(nil),   // 5: proto_products.CommitProductsRequest
	(*CommitProductsResponse)(nil),  // 6: proto_products.CommitProductsResponse
	(*GetProductByIDRequest)(nil),   // 7: proto_products.GetProductByIDRequest
	(*GetProductByIDResponse)(nil),  // 8: proto_products.GetProductByIDResponse
	(*GetProductsByIDRequest)(nil),  // 9: proto_products.GetProductsByIDRequest
	(*GetProductsByIDResponse)(nil), // 10: proto_products.GetProductsByIDResponse
	(*Product)(nil),                 // 11: proto_products.Product
}
var file_proto_products_products_proto_depIdxs = []int32{
	1,  // 0: proto_products.ReserveProductsRequest.products:type_name -> proto_products.ProductSaga
	1,  // 1: proto_products.ReleaseProductsRequest.products:type_name -> proto_products.ProductSaga
	1,  // 2: proto_products.CommitProductsRequest.products:type_name -> proto_products.ProductSaga
	11, // 3: proto_products.GetProductByIDResponse.product:type_name -> proto_products.Product
	11, // 4: proto_products.GetProductsByIDResponse.products:type_name -> proto_products.Product
	7,  // 5: proto_products.Products.GetProductByID:input_type -> proto_products.GetProductByIDRequest
	9,  // 6: proto_products.Products.GetProducts:input_type -> proto_products.GetProductsByIDRequest
	0,  // 7: proto_products.SagaProducts.ReserveProducts:input_type -> proto_products.ReserveProductsRequest
	3,  // 8: proto_products.SagaProducts.ReleaseProducts:input_type -> proto_products.ReleaseProductsRequest
	5,  // 9: proto_products.SagaProducts.CommitProducts:input_type -> proto_products.CommitProductsRequest
	8,  // 10: proto_products.Products.GetProductByID:output_type -> proto_products.GetProductByIDResponse
	10, // 11: proto_products.Products.GetProducts:output_type -> proto_products.GetProductsByIDResponse
	2,  // 12: proto_products.SagaProducts.ReserveProducts:output_type -> proto_products.ReserveProductsResponse
	4,  // 13: proto_products.SagaProducts.ReleaseProducts:output_type -> proto_products.ReleaseProductsResponse
	6,  // 14: proto_products.SagaProducts.CommitProducts:output_type -> proto_products.CommitProductsResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_products_products_proto_init() }
func file_proto_products_products_proto_init() {
	if File_proto_products_products_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_products_products_proto_rawDesc), len(file_proto_products_products_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_products_products_proto_goTypes,
		DependencyIndexes: file_proto_products_products_proto_depIdxs,
		MessageInfos:      file_proto_products_products_proto_msgTypes,
	}.Build()
	File_proto_products_products_proto = out.File
	file_proto_products_products_proto_goTypes = nil
	file_proto_products_products_proto_depIdxs = nil
}
