// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: products/products.proto

package products

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Products_GetProductByID_FullMethodName = "/proto_products.Products/GetProductByID"
	Products_GetProducts_FullMethodName    = "/proto_products.Products/GetProducts"
)

// ProductsClient is the client API for Products service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Products service provides product catalog operations for inter-service communication
type ProductsClient interface {
	// GetProductByID retrieves a single product by its ID
	GetProductByID(ctx context.Context, in *GetProductByIDRequest, opts ...grpc.CallOption) (*GetProductByIDResponse, error)
	// GetProducts retrieves multiple products by their IDs (batch operation)
	GetProducts(ctx context.Context, in *GetProductsByIDRequest, opts ...grpc.CallOption) (*GetProductsByIDResponse, error)
}

type productsClient struct {
	cc grpc.ClientConnInterface
}

func NewProductsClient(cc grpc.ClientConnInterface) ProductsClient {
	return &productsClient{cc}
}

func (c *productsClient) GetProductByID(ctx context.Context, in *GetProductByIDRequest, opts ...grpc.CallOption) (*GetProductByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductByIDResponse)
	err := c.cc.Invoke(ctx, Products_GetProductByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) GetProducts(ctx context.Context, in *GetProductsByIDRequest, opts ...grpc.CallOption) (*GetProductsByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductsByIDResponse)
	err := c.cc.Invoke(ctx, Products_GetProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductsServer is the server API for Products service.
// All implementations must embed UnimplementedProductsServer
// for forward compatibility.
//
// Products service provides product catalog operations for inter-service communication
type ProductsServer interface {
	// GetProductByID retrieves a single product by its ID
	GetProductByID(context.Context, *GetProductByIDRequest) (*GetProductByIDResponse, error)
	// GetProducts retrieves multiple products by their IDs (batch operation)
	GetProducts(context.Context, *GetProductsByIDRequest) (*GetProductsByIDResponse, error)
	mustEmbedUnimplementedProductsServer()
}

// UnimplementedProductsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductsServer struct{}

func (UnimplementedProductsServer) GetProductByID(context.Context, *GetProductByIDRequest) (*GetProductByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductByID not implemented")
}
func (UnimplementedProductsServer) GetProducts(context.Context, *GetProductsByIDRequest) (*GetProductsByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProducts not implemented")
}
func (UnimplementedProductsServer) mustEmbedUnimplementedProductsServer() {}
func (UnimplementedProductsServer) testEmbeddedByValue()                  {}

// UnsafeProductsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductsServer will
// result in compilation errors.
type UnsafeProductsServer interface {
	mustEmbedUnimplementedProductsServer()
}

func RegisterProductsServer(s grpc.ServiceRegistrar, srv ProductsServer) {
	// If the following call panics, it indicates UnimplementedProductsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Products_ServiceDesc, srv)
}

func _Products_GetProductByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).GetProductByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_GetProductByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).GetProductByID(ctx, req.(*GetProductByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_GetProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductsByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).GetProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_GetProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).GetProducts(ctx, req.(*GetProductsByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Products_ServiceDesc is the grpc.ServiceDesc for Products service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Products_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto_products.Products",
	HandlerType: (*ProductsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProductByID",
			Handler:    _Products_GetProductByID_Handler,
		},
		{
			MethodName: "GetProducts",
			Handler:    _Products_GetProducts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "products/products.proto",
}

const (
	SagaProducts_ReserveProducts_FullMethodName = "/proto_products.SagaProducts/ReserveProducts"
	SagaProducts_ReleaseProducts_FullMethodName = "/proto_products.SagaProducts/ReleaseProducts"
	SagaProducts_CommitProducts_FullMethodName  = "/proto_products.SagaProducts/CommitProducts"
)

// SagaProductsClient is the client API for SagaProducts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SagaProducts service implements saga pattern for distributed transactions
// Used by saga-orchestrator to manage product inventory in multi-step transactions
type SagaProductsClient interface {
	// ReserveProducts reserves product inventory (saga prepare phase)
	// This is the first step in a distributed transaction
	ReserveProducts(ctx context.Context, in *ReserveProductsRequest, opts ...grpc.CallOption) (*ReserveProductsResponse, error)
	// ReleaseProducts releases previously reserved inventory (saga rollback/compensate)
	// Called when transaction needs to be rolled back
	ReleaseProducts(ctx context.Context, in *ReleaseProductsRequest, opts ...grpc.CallOption) (*ReleaseProductsResponse, error)
	// CommitProducts commits the reservation and decrements inventory (saga commit)
	// Final step when transaction is successful
	CommitProducts(ctx context.Context, in *CommitProductsRequest, opts ...grpc.CallOption) (*CommitProductsResponse, error)
}

type sagaProductsClient struct {
	cc grpc.ClientConnInterface
}

func NewSagaProductsClient(cc grpc.ClientConnInterface) SagaProductsClient {
	return &sagaProductsClient{cc}
}

func (c *sagaProductsClient) ReserveProducts(ctx context.Context, in *ReserveProductsRequest, opts ...grpc.CallOption) (*ReserveProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveProductsResponse)
	err := c.cc.Invoke(ctx, SagaProducts_ReserveProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sagaProductsClient) ReleaseProducts(ctx context.Context, in *ReleaseProductsRequest, opts ...grpc.CallOption) (*ReleaseProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseProductsResponse)
	err := c.cc.Invoke(ctx, SagaProducts_ReleaseProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sagaProductsClient) CommitProducts(ctx context.Context, in *CommitProductsRequest, opts ...grpc.CallOption) (*CommitProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitProductsResponse)
	err := c.cc.Invoke(ctx, SagaProducts_CommitProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SagaProductsServer is the server API for SagaProducts service.
// All implementations must embed UnimplementedSagaProductsServer
// for forward compatibility.
//
// SagaProducts service implements saga pattern for distributed transactions
// Used by saga-orchestrator to manage product inventory in multi-step transactions
type SagaProductsServer interface {
	// ReserveProducts reserves product inventory (saga prepare phase)
	// This is the first step in a distributed transaction
	ReserveProducts(context.Context, *ReserveProductsRequest) (*ReserveProductsResponse, error)
	// ReleaseProducts releases previously reserved inventory (saga rollback/compensate)
	// Called when transaction needs to be rolled back
	ReleaseProducts(context.Context, *ReleaseProductsRequest) (*ReleaseProductsResponse, error)
	// CommitProducts commits the reservation and decrements inventory (saga commit)
	// Final step when transaction is successful
	CommitProducts(context.Context, *CommitProductsRequest) (*CommitProductsResponse, error)
	mustEmbedUnimplementedSagaProductsServer()
}

// UnimplementedSagaProductsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSagaProductsServer struct{}

func (UnimplementedSagaProductsServer) ReserveProducts(context.Context, *ReserveProductsRequest) (*ReserveProductsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReserveProducts not implemented")
}
func (UnimplementedSagaProductsServer) ReleaseProducts(context.Context, *ReleaseProductsRequest) (*ReleaseProductsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseProducts not implemented")
}
func (UnimplementedSagaProductsServer) CommitProducts(context.Context, *CommitProductsRequest) (*CommitProductsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitProducts not implemented")
}
func (UnimplementedSagaProductsServer) mustEmbedUnimplementedSagaProductsServer() {}
func (UnimplementedSagaProductsServer) testEmbeddedByValue()                      {}

// UnsafeSagaProductsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SagaProductsServer will
// result in compilation errors.
type UnsafeSagaProductsServer interface {
	mustEmbedUnimplementedSagaProductsServer()
}

func RegisterSagaProductsServer(s grpc.ServiceRegistrar, srv SagaProductsServer) {
	// If the following call panics, it indicates UnimplementedSagaProductsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SagaProducts_ServiceDesc, srv)
}

func _SagaProducts_ReserveProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SagaProductsServer).ReserveProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SagaProducts_ReserveProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SagaProductsServer).ReserveProducts(ctx, req.(*ReserveProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SagaProducts_ReleaseProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SagaProductsServer).ReleaseProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SagaProducts_ReleaseProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SagaProductsServer).ReleaseProducts(ctx, req.(*ReleaseProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SagaProducts_CommitProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SagaProductsServer).CommitProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SagaProducts_CommitProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SagaProductsServer).CommitProducts(ctx, req.(*CommitProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SagaProducts_ServiceDesc is the grpc.ServiceDesc for SagaProducts service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SagaProducts_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto_products.SagaProducts",
	HandlerType: (*SagaProductsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReserveProducts",
			Handler:    _SagaProducts_ReserveProducts_Handler,
		},
		{
			MethodName: "ReleaseProducts",
			Handler:    _SagaProducts_ReleaseProducts_Handler,
		},
		{
			MethodName: "CommitProducts",
			Handler:    _SagaProducts_CommitProducts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "products/products.proto",
}
